// Code generated by mockery v1.0.0. DO NOT EDIT.

package httputils

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

// ListenAndServe provides a mock function with given fields:
func (_m *MockServer) ListenAndServe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockServer) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
