// Code generated by mockery v1.0.0. DO NOT EDIT.

package presenters

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockErrorPresenter is an autogenerated mock type for the ErrorPresenter type
type MockErrorPresenter struct {
	mock.Mock
}

// PresentError provides a mock function with given fields: writer, statusCode, err
func (_m *MockErrorPresenter) PresentError(writer http.ResponseWriter, statusCode int, err error) error {
	ret := _m.Called(writer, statusCode, err)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, int, error) error); ok {
		r0 = rf(writer, statusCode, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
