// Code generated by mockery v1.0.0. DO NOT EDIT.

package presenters

import entities "github.com/thewizardplusplus/go-link-shortener/entities"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockLinkPresenter is an autogenerated mock type for the LinkPresenter type
type MockLinkPresenter struct {
	mock.Mock
}

// PresentLink provides a mock function with given fields: writer, link
func (_m *MockLinkPresenter) PresentLink(writer http.ResponseWriter, link entities.Link) error {
	ret := _m.Called(writer, link)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, entities.Link) error); ok {
		r0 = rf(writer, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
