// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package usecases

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/thewizardplusplus/go-link-shortener-backend/entities"
)

// MockLinkGetter is an autogenerated mock type for the LinkGetter type
type MockLinkGetter struct {
	mock.Mock
}

// GetLink provides a mock function with given fields: query
func (_m *MockLinkGetter) GetLink(query string) (entities.Link, error) {
	ret := _m.Called(query)

	var r0 entities.Link
	if rf, ok := ret.Get(0).(func(string) entities.Link); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Get(0).(entities.Link)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
