// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package usecases

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/thewizardplusplus/go-link-shortener-backend/entities"
)

// MockLinkSetter is an autogenerated mock type for the LinkSetter type
type MockLinkSetter struct {
	mock.Mock
}

// SetLink provides a mock function with given fields: link
func (_m *MockLinkSetter) SetLink(link entities.Link) error {
	ret := _m.Called(link)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Link) error); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
