// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package handlers

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockErrorPresenter is an autogenerated mock type for the ErrorPresenter type
type MockErrorPresenter struct {
	mock.Mock
}

// PresentError provides a mock function with given fields: writer, request, statusCode, err
func (_m *MockErrorPresenter) PresentError(writer http.ResponseWriter, request *http.Request, statusCode int, err error) {
	_m.Called(writer, request, statusCode, err)
}
