// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package handlers

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/thewizardplusplus/go-link-shortener-backend/entities"
)

// MockLinkCreator is an autogenerated mock type for the LinkCreator type
type MockLinkCreator struct {
	mock.Mock
}

// CreateLink provides a mock function with given fields: url
func (_m *MockLinkCreator) CreateLink(url string) (entities.Link, error) {
	ret := _m.Called(url)

	var r0 entities.Link
	if rf, ok := ret.Get(0).(func(string) entities.Link); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(entities.Link)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
