// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockErrorPresenter is an autogenerated mock type for the ErrorPresenter type
type MockErrorPresenter struct {
	mock.Mock
}

// PresentError provides a mock function with given fields: writer, statusCode, err
func (_m *MockErrorPresenter) PresentError(writer http.ResponseWriter, statusCode int, err error) {
	_m.Called(writer, statusCode, err)
}
